<?php
return [
  'languages' => [
    0 => [
      'name' => 'Tiếng Việt',
      'locale' => 'vi',
      'timezone' => 'Asia/Ho_Chi_Minh',
      'flag' => 'vi',
    ],
  ],
  'language_default' => 'vi',
  'theme_default' => 'default',
  'current_version' => '4.0.21',
  'latest_version' => '4.0.2',
  'seo_plugin' => true,
  'jobs' => [
    'Bác sĩ' => 'Bác sĩ',
    'Dược sĩ' => 'Dược sĩ',
    'Điều dưỡng' => 'Điều dưỡng',
    'Nhân viên MSD' => 'Nhân viên MSD',
    'Sinh viên y khoa' => 'Sinh viên y khoa',
    'Khác' => 'Khác',
  ],
  'hospitals' => [
    'BỆNH VIỆN AN BÌNH' => 'BỆNH VIỆN AN BÌNH',
    'BỆNH VIỆN ĐA KHOA TƯ NHÂN AN SINH' => 'BỆNH VIỆN ĐA KHOA TƯ NHÂN AN SINH',
    'BỆNH VIỆN QUÂN DÂN MIỀN ĐÔNG' => 'BỆNH VIỆN QUÂN DÂN MIỀN ĐÔNG',
    'BỆNH VIỆN BƯU ĐIỆN 2' => 'BỆNH VIỆN BƯU ĐIỆN 2',
    'BỆNH VIỆN UNG BƯỚU TP.HCM' => 'BỆNH VIỆN UNG BƯỚU TP.HCM',
    'BỆNH VIỆN TRUYỀN MÁU HUYẾT HỌC' => 'BỆNH VIỆN TRUYỀN MÁU HUYẾT HỌC',
    'BỆNH VIỆN TÂM THẦN TP.HCM' => 'BỆNH VIỆN TÂM THẦN TP.HCM',
    'BỆNH VIỆN Y HỌC CỔ TRUYỀN' => 'BỆNH VIỆN Y HỌC CỔ TRUYỀN',
    'BỆNH VIỆN CHẤN THƯƠNG CHỈNH HÌNH' => 'BỆNH VIỆN CHẤN THƯƠNG CHỈNH HÌNH',
    'BÌNH DÂN - BỆNH VIỆN BÌNH DÂN' => 'BÌNH DÂN - BỆNH VIỆN BÌNH DÂN',
    'BỆNH VIỆN BỆNH NHIỆT ĐỚI' => 'BỆNH VIỆN BỆNH NHIỆT ĐỚI',
    'BỆNH VIỆN DA LIỄU' => 'BỆNH VIỆN DA LIỄU',
    'BỆNH VIỆN MẮT TP.HCM' => 'BỆNH VIỆN MẮT TP.HCM',
    'BỆNH VIỆN TAI MŨI HỌNG TP.HCM' => 'BỆNH VIỆN TAI MŨI HỌNG TP.HCM',
    'BỆNH VIỆN TRƯỜNG ĐH Y DƯỢC' => 'BỆNH VIỆN TRƯỜNG ĐH Y DƯỢC',
    'BỆNH VIỆN CHỢ RẪY' => 'BỆNH VIỆN CHỢ RẪY',
  ],
  'specialists' => [
    'Chấn thương chỉnh hình' => 'Chấn thương chỉnh hình',
    'Da liễu' => 'Da liễu',
    'Dược lâm sàng' => 'Dược lâm sàng',
    'Đau' => 'Đau',
    'Gan mật' => 'Gan mật',
    'Gây mê' => 'Gây mê',
    'Huyết học' => 'Huyết học',
    'Hồi sức' => 'Hồi sức',
    'Khớp' => 'Khớp',
    'Nhi khoa' => 'Nhi khoa',
    'Nhiễm' => 'Nhiễm',
    'Nội tiết' => 'Nội tiết',
    'Phòng khám' => 'Phòng khám',
    'Phổi' => 'Phổi',
    'Phụ Sản' => 'Phụ Sản',
    'Phục hồi chức năng' => 'Phục hồi chức năng',
    'Răng/Hàm/Mặt' => 'Răng/Hàm/Mặt',
    'Tai mũi họng' => 'Tai mũi họng',
    'Thần kinh' => 'Thần kinh',
    'Thận' => 'Thận',
    'Tim mạch' => 'Tim mạch',
    'Tiêu hóa' => 'Tiêu hóa',
    'Tiết niệu' => 'Tiết niệu',
    'Tâm lí' => 'Tâm lí',
    'Tổng quát' => 'Tổng quát',
    'Ung thư' => 'Ung thư',
    'Vi sinh' => 'Vi sinh',
    'Vô sinh' => 'Vô sinh',
    'Vật lý trị liệu' => 'Vật lý trị liệu',
    'X-quang' => 'X-quang',
    'Y học dân tộc' => 'Y học dân tộc',
    'Y tế cộng đồng' => 'Y tế cộng đồng',
  ],
];